treewide: Replace _unused with _o_unused
A header file in the Linux kernel on powerpc uses the variable name
_unused. This causes the following compile error:
```
In file included from /staging_dir/toolchain-powerpc_8548_gcc-14.3.0_musl/include/signal.h:48,
                 from /staging_dir/target-powerpc_8548_musl/usr/include/libubox/uloop.h:25,
                 from /staging_dir/target-powerpc_8548_musl/usr/include/libubus.h:24,
                 from /build_dir/target-powerpc_8548_musl/odhcp6c-2025.11.04~b3e1db42/src/ubus.h:67,
                 from /build_dir/target-powerpc_8548_musl/odhcp6c-2025.11.04~b3e1db42/src/ubus.c:73:
/staging_dir/toolchain-powerpc_8548_gcc-14.3.0_musl/include/bits/signal.h:27:30: error: expected identifier or '(' before '[' token
   27 |         unsigned long _unused[4];
      |                              ^
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:62: /build_dir/target-powerpc_8548_musl/odhcp6c-2025.11.04~b3e1db42/.built] Error 1
```

Use _o_unused instead to avoid such conflicts.

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>